repos:
  # Automatically fix issues.

  ## Python, Polyglot, Git, pre-commit
  - repo: https://github.com/ScribeMD/pre-commit-hooks
    rev: 0.16.3
    hooks:
      - id: no-merge-commits
      # - id: asdf-install
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
      - id: pre-commit-install

  ## Markdown
  - repo: https://github.com/frnmst/md-toc
    rev: 8.2.3
    hooks:
      - id: md-toc

  ## Python, TOML, Polyglot, Git
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      ### Automatically fix issues.
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: \.dictionary\.txt
        args: [--ignore-case, --unique]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

      ### Check for issues.
      - id: check-added-large-files
        args: [--enforce-all]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: forbid-submodules
      - id: no-commit-to-branch

  # Check for issues.

  ## Natural language
  - repo: https://github.com/PrincetonUniversity/blocklint
    rev: v0.2.4
    hooks:
      - id: blocklint

  ## Git
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: check-mailmap
      - id: forbid-binary
      - id: git-check
