name: "Install dependencies with Poetry"
description: "Install dependencies using Poetry."
author: "@ouhammmourachid"
branding:
  icon: "truck"
  color: "blue"

inputs:
  python-version:
    description: "The version of Python to use."
    required: true
    default: "3.10"
  poetry-version:
    description: "The version of Poetry to use."
    required: true
    default: "latest"
  extra-args:
    description: "Extra arguments to pass to the `poetry install` command."
    required: false
    default: ""
  install-dependencies:
    description: "Whether to install dependencies or not."
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    # Step 1: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # Step 2: Install Poetry
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.4.1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true
    - name: Add Poetry to PATH
      run: |
        echo "$env:USERPROFILE\.local\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: pwsh
      if: runner.os == 'Windows'

    # Step 4: Cache Poetry dependencies
    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: pypoetry-${{inputs.python-version}}-${{env.poetry-version}}-${{runner.os}}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          pypoetry-${{inputs.python-version}}-${{inputs.poetry-version}}-${{runner.os}}-

    # Step 5: Install dependencies
    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: |
        ls -all .venv
        source $VENV
        poetry env use $pythonLocation\\python.exe
        poetry install ${{ inputs.extra-args }}
        poetry show
      shell: bash
