name: 'Install dependencies with Poetry'
description: 'Install dependencies using Poetry.'
author: '@ouhammmourachid'
branding:
  icon: 'truck'
  color: 'blue'


inputs:
  python-version:
    description: 'The version of Python to use.'
    required: true
    default: '3.10'
  poetry-version:
    description: 'The version of Poetry to use.'
    required: true
    default: 'latest'
  

runs:
  using: 'composite'
  steps:
  
    # Step 1: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    # Step 2: Install Poetry
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        version: ${{ inputs.poetry-version }}
    
    - name: Add Poetry to PATH
      run: |
        echo "C:\Users\runneradmin\.local\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: pwsh
      if: runner.os == 'Windows'

    # Step 3: Cache Poetry dependencies
    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: pypoetry-${{inputs.python-version}}-${{inputs.poetry-version}}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          pypoetry-${{inputs.python-version}}-${{inputs.poetry-version}}-
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        poetry install
        poetry show
      shell: bash
    